In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/full_dataset_one_row_per_cycle_fw_indexing_48days.csv')

In [ ]:
df = df.drop(columns=['Unnamed: 0'])

In [ ]:
df.head()

,hub_id,cycle_index,cycle_length,cycle_status,max_LH_day,max_LH_day_bw,day0_LH,day1_LH,day2_LH,day3_LH,...,day38_PDG,day39_PDG,day40_PDG,day41_PDG,day42_PDG,day43_PDG,day44_PDG,day45_PDG,day46_PDG,day47_PDG
0,U2CCD5D16315123,31.0,35,1,21.0,-14.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U303F6B17404145,7.0,19,1,5.0,-14.0,7.260,11.30,9.81,10.81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U2E649816722750,19.0,31,1,15.0,-16.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U2F50A717152551,10.0,26,1,20.0,-6.0,3.625,2.13,5.84,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U2F191017106760,19.0,26,1,15.0,-11.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# keep hub_id, cycle_length, cycle_index, cycle_status, max_LH_day, max_LH_day_bw
# TRUE == data present
# FALSE == data not present
# NaN == end of cycle (as cycle length permits)

In [ ]:
def bool_up_to_cycle_length(df):
    hormones = ['LH', 'PDG', 'E3G']
    for hormone in hormones:
      # hormones max day 47, so range 48
        for day in range(48):
            col_name = f"day{day}_{hormone}"
            if col_name in df.columns:
                # Set NaN if day exceeds cycle length
                df.loc[day > df['cycle_length'], col_name] = np.nan
                # Set True if data is present and within cycle length
                df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
                # Set False if data is missing and within cycle length
                df.loc[df[col_name].isna() & (day <= df['cycle_length']), col_name] = False
    return df

In [ ]:
df = bool_up_to_cycle_length(df)

<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True
<ipython-input-42-06c9f206d324>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[col_name].notna() & (day <= df['cycle_length']), col_name] = True

In [ ]:
df.head()

,hub_id,cycle_index,cycle_length,cycle_status,max_LH_day,max_LH_day_bw,day0_LH,day1_LH,day2_LH,day3_LH,...,day38_PDG,day39_PDG,day40_PDG,day41_PDG,day42_PDG,day43_PDG,day44_PDG,day45_PDG,day46_PDG,day47_PDG
0,U2CCD5D16315123,31.0,35,1,21.0,-14.0,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U303F6B17404145,7.0,19,1,5.0,-14.0,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U2E649816722750,19.0,31,1,15.0,-16.0,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U2F50A717152551,10.0,26,1,20.0,-6.0,True,True,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U2F191017106760,19.0,26,1,15.0,-11.0,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from google.colab import files
df.to_csv('full_dataset_missing_vals_one_row_per_cycle_fw_indexing_48days.csv', index=False)
files.download('full_dataset_missing_vals_one_row_per_cycle_fw_indexing_48days.csv')

In [ ]:
df.head()

,hub_id,cycle_index,cycle_length,cycle_status,max_LH_day,max_LH_day_bw,day0_LH,day1_LH,day2_LH,day3_LH,...,day38_PDG,day39_PDG,day40_PDG,day41_PDG,day42_PDG,day43_PDG,day44_PDG,day45_PDG,day46_PDG,day47_PDG
0,U2CCD5D16315123,31.0,35,1,21.0,-14.0,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U303F6B17404145,7.0,19,1,5.0,-14.0,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U2E649816722750,19.0,31,1,15.0,-16.0,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U2F50A717152551,10.0,26,1,20.0,-6.0,True,True,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U2F191017106760,19.0,26,1,15.0,-11.0,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN